name: Run E2E tests

on: [push]

jobs:
  run-e2e-tests:
    name: Run E2E tests
    runs-on: ubuntu-latest

    services:
      gym-app:
        image: bitnami/postgresql
        ports:
          - 5432:5432
        env:
          POSTGRESQL_USERNAME: docker
          POSTGRESQL_PASSWORD: docker

    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '23'
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Run test
        run: npm run test:e2e
        env:
          JWT_SECRET: secret-test
          DATABASE_URL: 'postgresql://docker:docker@localhost:5432/gym-app?schema=public'
